# Generated by Django 4.2 on 2023-05-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='levelupapi.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='num_of_players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(),
        ),
    ]
